/**
 * AgentLens NL -> SQL Query Engine
 *
 * Converts a natural-language question into a read-only SQL query constrained
 * to an allowlisted schema, then executes it against the mock seed (offline)
 * or a live Supabase instance (online).
 *
 * LLM integration note:
 *   In production this module calls Claude (Anthropic) with tenant data.
 *   The prompt includes the allowlisted schema and a strict system instruction
 *   that permits only SELECT statements with no subqueries on non-allowlisted
 *   tables. Never route tenant data through Ollama or any third-party model.
 *
 *   Stub: the `translateToSql` function below returns deterministic SQL for
 *   well-known question patterns, allowing the UI to run fully offline.
 */

import type { Agent, AgentMetricDaily, Alert, Capacity, ComplianceViolation } from '@/lib/types';
import {
  mockAgents,
  mockMetrics,
  mockAlerts,
  mockCapacity,
  mockViolations,
  mockEnvironments,
} from '@/lib/mock/seed';

// ---------------------------------------------------------------------------
// Allowlisted schema (read-only; the LLM must only reference these tables/cols)
// ---------------------------------------------------------------------------
export const ALLOWLISTED_SCHEMA = `
Tables and columns the query engine may access (read-only SELECT only):

agents           (envId, botId, name, ownerName, ownerEmail, state, createdOn,
                  modifiedOn, lastActivity, kind, lifecycle)
environments     (id, name, type, isDefault, region, orgUrl)
agent_metrics    (envId, botId, date, messageCount, sessionCount, estimatedCost,
                  modelMeter, projectedMonthly)
alerts           (id, type, severity, envId, botId, message, state, createdAt)
capacity         (envId, creditLimit, creditUsed, pct, overage)
violations       (id, agentRef, ruleId, severity, state, detectedAt)

Constraints:
- Only SELECT is allowed.
- No JOINs to tables outside this list.
- No subqueries referencing tables outside this list.
- No WRITE operations (INSERT, UPDATE, DELETE, DROP, TRUNCATE).
`.trim();

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------
export interface NlQueryRequest {
  /** Free-text question from the user */
  question: string;
  /** Optional: limit result rows (default 50) */
  maxRows?: number;
}

export interface NlQueryResult {
  /** The SQL generated by the LLM (or stub) */
  sql: string;
  /** Column headers derived from the result rows */
  columns: string[];
  /** Result rows - each row is a record of column->value */
  rows: Record<string, unknown>[];
  /** True when the result comes from the offline mock engine */
  isMock: boolean;
  /** Error message if query could not be translated or executed */
  error?: string;
}

// ---------------------------------------------------------------------------
// LLM stub: translate a natural-language question to SQL
//
// In production replace this function body with an Anthropic Claude API call:
//
//   const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
//   const message = await anthropic.messages.create({
//     model: 'claude-opus-4-5',
//     max_tokens: 512,
//     system: `You are a read-only SQL assistant. Schema:\n${ALLOWLISTED_SCHEMA}\n
//              Rules: produce exactly one SELECT statement, no semicolon,
//              only reference the tables in the schema.`,
//     messages: [{ role: 'user', content: question }],
//   });
//   return extractSql(message.content);
// ---------------------------------------------------------------------------
function translateToSql(question: string): string {
  const q = question.toLowerCase();

  if (q.includes('overage') || q.includes('over limit') || q.includes('over budget')) {
    return 'SELECT * FROM capacity WHERE overage = true';
  }
  if (q.includes('orphan') || q.includes('no owner') || q.includes('without owner')) {
    return "SELECT * FROM agents WHERE ownerEmail IS NULL AND state = 'Active'";
  }
  if (q.includes('critical') && q.includes('alert')) {
    return "SELECT * FROM alerts WHERE severity = 'critical' AND state = 'open'";
  }
  if (q.includes('prod') && q.includes('agent')) {
    return "SELECT * FROM agents WHERE lifecycle = 'prod'";
  }
  if (q.includes('poc') && q.includes('agent')) {
    return "SELECT * FROM agents WHERE lifecycle = 'poc'";
  }
  if (q.includes('pilot') && q.includes('agent')) {
    return "SELECT * FROM agents WHERE lifecycle = 'pilot'";
  }
  if (q.includes('open violation') || (q.includes('violation') && q.includes('open'))) {
    return "SELECT * FROM violations WHERE state = 'open'";
  }
  if (q.includes('cost') || q.includes('spend') || q.includes('metric')) {
    return 'SELECT * FROM agent_metrics ORDER BY estimatedCost DESC';
  }
  if (q.includes('inactive') || q.includes('idle')) {
    return "SELECT * FROM agents WHERE state = 'Inactive'";
  }
  if (q.includes('environment') || q.includes('env')) {
    return 'SELECT * FROM environments';
  }
  if (q.includes('alert')) {
    return 'SELECT * FROM alerts ORDER BY createdAt DESC';
  }
  // Fallback: return all agents
  return 'SELECT * FROM agents';
}

// ---------------------------------------------------------------------------
// In-memory mock SQL executor
//
// Supports a small subset of SQL patterns generated by `translateToSql`.
// Parses table name + optional WHERE clause (simple key=value comparisons).
// ---------------------------------------------------------------------------
type AnyRow = Record<string, unknown>;

function asList(table: string): AnyRow[] {
  switch (table) {
    case 'agents':
      return mockAgents as unknown as AnyRow[];
    case 'agent_metrics':
      return mockMetrics as unknown as AnyRow[];
    case 'alerts':
      return mockAlerts as unknown as AnyRow[];
    case 'capacity':
      return mockCapacity as unknown as AnyRow[];
    case 'violations':
      return mockViolations as unknown as AnyRow[];
    case 'environments':
      return mockEnvironments as unknown as AnyRow[];
    default:
      return [];
  }
}

interface WhereClause {
  field: string;
  op: '=' | '!=' | 'IS NULL' | 'IS NOT NULL';
  value: string | boolean | null;
}

function parseWhere(whereStr: string): WhereClause[] {
  const clauses: WhereClause[] = [];
  // Split on AND (only simple AND chains are supported)
  const parts = whereStr.split(/\s+AND\s+/i);

  for (const part of parts) {
    const trimmed = part.trim();

    // IS NULL
    const isNullMatch = trimmed.match(/^(\w+)\s+IS\s+NULL$/i);
    if (isNullMatch) {
      clauses.push({ field: isNullMatch[1], op: 'IS NULL', value: null });
      continue;
    }

    // IS NOT NULL
    const isNotNullMatch = trimmed.match(/^(\w+)\s+IS\s+NOT\s+NULL$/i);
    if (isNotNullMatch) {
      clauses.push({ field: isNotNullMatch[1], op: 'IS NOT NULL', value: null });
      continue;
    }

    // equality: field = 'value' or field = true/false
    const eqMatch = trimmed.match(/^(\w+)\s*=\s*(.+)$/i);
    if (eqMatch) {
      const rawVal = eqMatch[2].trim().replace(/^['"]|['"]$/g, '');
      const value: string | boolean =
        rawVal === 'true' ? true : rawVal === 'false' ? false : rawVal;
      clauses.push({ field: eqMatch[1], op: '=', value });
      continue;
    }
  }

  return clauses;
}

function applyWhere(rows: AnyRow[], clauses: WhereClause[]): AnyRow[] {
  return rows.filter((row) =>
    clauses.every((clause) => {
      const val = row[clause.field];
      switch (clause.op) {
        case 'IS NULL':
          return val === null || val === undefined;
        case 'IS NOT NULL':
          return val !== null && val !== undefined;
        case '=':
          // eslint-disable-next-line eqeqeq
          return val == clause.value;
        case '!=':
          // eslint-disable-next-line eqeqeq
          return val != clause.value;
        default:
          return true;
      }
    })
  );
}

function executeMockSql(sql: string, maxRows: number): { columns: string[]; rows: AnyRow[] } {
  const normalized = sql.replace(/\s+/g, ' ').trim();

  // Parse: SELECT * FROM <table> [WHERE ...] [ORDER BY ...]
  const match = normalized.match(
    /^SELECT\s+\*\s+FROM\s+(\w+)(?:\s+WHERE\s+(.+?))?(?:\s+ORDER\s+BY\s+.+)?$/i
  );

  if (!match) {
    return { columns: [], rows: [] };
  }

  const tableName = match[1].toLowerCase();
  const whereStr = match[2];

  let rows = asList(tableName);

  if (whereStr) {
    const clauses = parseWhere(whereStr);
    rows = applyWhere(rows, clauses);
  }

  // Slice to maxRows
  rows = rows.slice(0, maxRows);

  // Derive columns from the first row
  const columns = rows.length > 0 ? Object.keys(rows[0]) : [];

  return { columns, rows };
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Translate a natural-language question to read-only SQL and execute it
 * against the mock seed data.
 *
 * In production: replace `translateToSql` with a Claude API call and
 * replace `executeMockSql` with a Supabase query.
 */
export async function runNlQuery(request: NlQueryRequest): Promise<NlQueryResult> {
  const maxRows = request.maxRows ?? 50;

  try {
    const sql = translateToSql(request.question);
    const { columns, rows } = executeMockSql(sql, maxRows);

    return {
      sql,
      columns,
      rows,
      isMock: true,
    };
  } catch (err) {
    return {
      sql: '',
      columns: [],
      rows: [],
      isMock: true,
      error: err instanceof Error ? err.message : 'Unknown error',
    };
  }
}

// Re-export types that the API route and page need
export type { Agent, AgentMetricDaily, Alert, Capacity, ComplianceViolation };
