'use client';

/**
 * Ask (AI) - natural-language Q&A grounded on REAL tenant data (Azure Resource Graph),
 * answered by Azure OpenAI. Configure AZURE_OPENAI_* in .env.local to enable.
 */

import React, { useState } from 'react';
import { Sparkles, Send, AlertTriangle, Database, Loader2 } from 'lucide-react';
import { Card, Badge, PageHeader, SectionTitle, Button } from '@/components/ui';

interface AskResponse {
  answer?: string;
  grounded?: boolean;
  dataSource?: string;
  error?: string;
  hint?: string;
}

const SUGGESTIONS = [
  'How many environments do I have and what are they?',
  'Do I have any Copilot Studio agents?',
  'Which environment is the default one?',
  'How many connectors are in my tenant?',
  'Summarize my tenant governance posture.',
  'Are there any agents without an owner?',
];

export default function AskPage() {
  const [question, setQuestion] = useState('');
  const [loading, setLoading] = useState(false);
  const [resp, setResp] = useState<AskResponse | null>(null);

  async function submit(q: string) {
    const trimmed = q.trim();
    if (!trimmed) return;
    setLoading(true);
    setResp(null);
    try {
      const res = await fetch('/api/ask', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ question: trimmed }),
      });
      setResp(await res.json());
    } catch {
      setResp({ error: 'Network error - could not reach /api/ask' });
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="mx-auto max-w-4xl p-8">
      <PageHeader
        icon={Sparkles}
        tone="violet"
        title="Ask (AI)"
        subtitle="Ask in plain English. Answers are generated by Azure OpenAI, grounded on your real tenant data (Azure Resource Graph) - never invented."
      />

      {/* Query box */}
      <Card className="p-4">
        <form
          onSubmit={(e) => { e.preventDefault(); void submit(question); }}
          className="space-y-3"
        >
          <textarea
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            placeholder="e.g. How many environments do I have and which is the default?"
            rows={3}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && (e.metaKey || e.ctrlKey)) { e.preventDefault(); void submit(question); }
            }}
            className="w-full resize-none rounded-lg border border-slate-700 bg-slate-950/60 px-4 py-3 text-sm text-slate-200 placeholder-slate-600 focus:outline-none focus:ring-2 focus:ring-violet-600/50"
          />
          <div className="flex items-center justify-between">
            <span className="text-xs text-slate-600">Cmd/Ctrl + Enter to send</span>
            <Button variant="primary" icon={loading ? Loader2 : Send} onClick={() => void submit(question)}>
              {loading ? 'Thinking...' : 'Ask'}
            </Button>
          </div>
        </form>
      </Card>

      {/* Suggestions */}
      <div className="mt-5">
        <SectionTitle>Try asking</SectionTitle>
        <div className="flex flex-wrap gap-2">
          {SUGGESTIONS.map((s) => (
            <button
              key={s}
              type="button"
              onClick={() => { setQuestion(s); void submit(s); }}
              className="rounded-full border border-slate-800 bg-slate-900/60 px-3 py-1.5 text-xs text-slate-400 transition-colors hover:border-violet-700/60 hover:text-violet-300"
            >
              {s}
            </button>
          ))}
        </div>
      </div>

      {/* Answer */}
      {loading && (
        <div className="mt-6 flex items-center gap-2 text-sm text-slate-400">
          <Loader2 className="h-4 w-4 animate-spin text-violet-400" /> Querying your tenant + asking Azure OpenAI...
        </div>
      )}

      {resp && !loading && (
        <div className="mt-6">
          {resp.answer ? (
            <Card className="p-5">
              <div className="mb-3 flex items-center gap-2">
                <Sparkles className="h-4 w-4 text-violet-400" />
                <span className="text-sm font-semibold text-slate-200">Answer</span>
                {resp.grounded ? (
                  <Badge variant="success" dot><Database className="h-3 w-3" /> grounded on live data</Badge>
                ) : (
                  <Badge variant="warning">no live data</Badge>
                )}
              </div>
              <div className="whitespace-pre-wrap text-sm leading-relaxed text-slate-300">{resp.answer}</div>
            </Card>
          ) : (
            <Card className="p-5">
              <div className="flex items-start gap-3">
                <AlertTriangle className="mt-0.5 h-5 w-5 shrink-0 text-amber-400" />
                <div>
                  <p className="font-semibold text-amber-300">{resp.error ?? 'Could not get an answer'}</p>
                  {resp.hint && <p className="mt-1 text-sm text-slate-400">{resp.hint}</p>}
                  {resp.error === 'Azure OpenAI not configured' && (
                    <pre className="mt-3 rounded-lg border border-slate-800 bg-slate-950 p-3 text-xs text-slate-400">{`AZURE_OPENAI_ENDPOINT=https://<resource>.openai.azure.com
AZURE_OPENAI_API_KEY=<secret key>
AZURE_OPENAI_DEPLOYMENT=gpt-4o`}</pre>
                  )}
                </div>
              </div>
            </Card>
          )}
        </div>
      )}
    </div>
  );
}
