<#
.SYNOPSIS
    Provisions the AgentLens-MCP Entra app registration used by the AgentLens
    declarative agent to call the AgentLens MCP server with Entra SSO.

.DESCRIPTION
    The second of the two app registrations AgentLens uses:

      A) AgentLens-Reader  - the data service principal (reads the five APIs).
                             Created by scripts/provision-reader-app.ps1.
      B) AgentLens-MCP     - THIS SCRIPT. Secures the MCP endpoint that the
                             declarative agent calls.

    The agent never touches tenant data directly. The chain is:

      user -> declarative agent -> AgentLens-MCP (SSO gate, this app)
           -> AgentLens-Reader (client credentials) -> the five read-only APIs

    So this app registration holds NO data permissions. Its only job is to
    prove who is calling the MCP server. All read permissions live on
    AgentLens-Reader.

    What this script creates / re-applies (idempotent by displayName):
      - The app registration (reused if it already exists).
      - Application ID URI: api://<appId>
      - An exposed delegated scope: access_as_user
      - Pre-authorized Microsoft 365 host clients, so users are not prompted
        for consent inside Copilot.
      - The service principal.
      - A client secret (--append, so existing secrets stay valid), optionally
        stored in Key Vault as MCP-CLIENT-SECRET.

.PARAMETER TenantId
    The Entra tenant ID to provision in. Must match the signed-in az context.

.PARAMETER McpUrl
    Public HTTPS URL of the hosted AgentLens MCP server, for example
    https://agentlens-mcp.azurecontainerapps.io/mcp
    Used for the redirect URI and echoed into the env block.

.PARAMETER KeyVaultName
    Optional. If supplied, the client secret is stored in this Key Vault.

.EXAMPLE
    ./scripts/provision-agent-mcp-app.ps1 `
        -TenantId  "<tenant-guid>" `
        -McpUrl    "https://agentlens-mcp.azurecontainerapps.io/mcp" `
        -KeyVaultName "kv-agentlens"

.NOTES
    Requires the Azure CLI (az) and a signed-in session with permission to
    create app registrations (Application Administrator or Global
    Administrator). Admin consent at the end needs a Global Administrator.
#>

[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory = $true)]
    [string] $TenantId,

    [Parameter(Mandatory = $true)]
    [string] $McpUrl,

    [Parameter(Mandatory = $false)]
    [string] $KeyVaultName,

    # Application ID URI generated by the Entra SSO auth config (Step 2 of the
    # Microsoft flow). Re-run the script with this once you have it; it is
    # appended to identifierUris. Token acquisition fails without it.
    [Parameter(Mandatory = $false)]
    [string] $SsoApplicationIdUri
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ---------------------------------------------------------------------------
# Helpers (same conventions as provision-reader-app.ps1)
# ---------------------------------------------------------------------------

function Write-Section([string]$Title) {
    Write-Host ""
    Write-Host "==========================================================" -ForegroundColor Cyan
    Write-Host "  $Title" -ForegroundColor Cyan
    Write-Host "==========================================================" -ForegroundColor Cyan
}

function Write-Step([string]$Msg) { Write-Host "  -> $Msg" -ForegroundColor Gray }
function Write-Done([string]$Msg) { Write-Host "  [OK] $Msg" -ForegroundColor Green }
function Write-Warn([string]$Msg) { Write-Host "  [WARN] $Msg" -ForegroundColor Yellow }

function Find-AppByName([string]$Name) {
    $result = az ad app list --display-name $Name --query "[0]" -o json 2>$null
    if ([string]::IsNullOrWhiteSpace($result) -or $result -eq "null") { return $null }
    return $result | ConvertFrom-Json
}

# PATCH the application object via Microsoft Graph. az CLI cannot express the
# nested api{} object, and passing raw JSON inline breaks on Windows quoting,
# so the body goes through a temp file.
function Invoke-GraphPatch([string]$ObjectId, [hashtable]$Body) {
    $tmp = [System.IO.Path]::GetTempFileName()
    try {
        ($Body | ConvertTo-Json -Depth 12) | Set-Content -Path $tmp -Encoding utf8
        az rest --method PATCH `
            --uri "https://graph.microsoft.com/v1.0/applications/$ObjectId" `
            --headers "Content-Type=application/json" `
            --body "@$tmp" --output none
    }
    finally {
        Remove-Item $tmp -ErrorAction SilentlyContinue
    }
}

function New-AppSecret([string]$AppId, [string]$Description) {
    $raw = az ad app credential reset `
        --id $AppId `
        --display-name $Description `
        --years 2 `
        --append `
        --query "password" -o tsv
    return $raw
}

function Set-KvSecret([string]$SecretName, [string]$SecretValue, [string]$Description) {
    if ([string]::IsNullOrWhiteSpace($KeyVaultName)) {
        Write-Warn "No -KeyVaultName supplied; $SecretName not stored in Key Vault."
        return
    }
    az keyvault secret set `
        --vault-name $KeyVaultName `
        --name $SecretName `
        --value $SecretValue `
        --description $Description `
        --output none
    Write-Done "Stored $SecretName in Key Vault $KeyVaultName"
}

# ---------------------------------------------------------------------------
# Pre-flight
# ---------------------------------------------------------------------------

Write-Section "Pre-flight"

$azVersion = az version --query '"azure-cli"' -o tsv 2>$null
if ([string]::IsNullOrWhiteSpace($azVersion)) {
    throw "Azure CLI not found. Install it from https://aka.ms/installazurecli"
}
Write-Done "Azure CLI $azVersion"

$currentTenant = az account show --query "tenantId" -o tsv 2>$null
if ([string]::IsNullOrWhiteSpace($currentTenant)) {
    throw "Not signed in. Run: az login --tenant $TenantId"
}
if ($currentTenant -ne $TenantId) {
    throw "Signed into tenant $currentTenant but -TenantId is $TenantId. Run: az login --tenant $TenantId"
}
Write-Done "Signed into tenant $TenantId"

if ($McpUrl -notmatch '^https://') {
    throw "-McpUrl must be an https:// URL. Copilot will not call a plaintext endpoint."
}

# Derive the origin (scheme + host) from the MCP URL for the redirect URI.
$mcpOrigin = ([System.Uri]$McpUrl).GetLeftPart([System.UriPartial]::Authority)
Write-Done "MCP origin $mcpOrigin"

# ---------------------------------------------------------------------------
# (B) AgentLens-MCP
# ---------------------------------------------------------------------------

Write-Section "(B) AgentLens-MCP - SSO gate for the declarative agent"

$mcpAppName = "AgentLens-MCP"
$existing = Find-AppByName $mcpAppName

if ($null -ne $existing) {
    $mcpAppId    = $existing.appId
    $mcpObjectId = $existing.id
    Write-Done "Reusing existing app registration ($mcpAppId)"
}
else {
    Write-Step "Creating app registration $mcpAppName"
    $created = az ad app create `
        --display-name $mcpAppName `
        --sign-in-audience "AzureADMyOrg" `
        --query "{appId:appId,id:id}" -o json | ConvertFrom-Json
    $mcpAppId    = $created.appId
    $mcpObjectId = $created.id
    Write-Done "Created ($mcpAppId)"
    # Entra needs a moment before the new object is patchable.
    Start-Sleep -Seconds 10
}

# ---- Service principal ----
$mcpSpExists = az ad sp show --id $mcpAppId --query "appId" -o tsv 2>$null
if ([string]::IsNullOrWhiteSpace($mcpSpExists)) {
    Write-Step "Creating service principal"
    az ad sp create --id $mcpAppId --output none
    Write-Done "Service principal created"
}
else {
    Write-Done "Service principal already exists"
}

# ---- Application ID URI + exposed scope ----
# Reuse the existing scope id when re-running, otherwise Entra rejects the
# patch as a duplicate scope value.
$existingScopeId = az ad app show --id $mcpAppId `
    --query "api.oauth2PermissionScopes[?value=='access_as_user'].id | [0]" -o tsv 2>$null

if ([string]::IsNullOrWhiteSpace($existingScopeId) -or $existingScopeId -eq "None") {
    $scopeId = [guid]::NewGuid().ToString()
    Write-Step "Creating delegated scope access_as_user ($scopeId)"
}
else {
    $scopeId = $existingScopeId
    Write-Done "Reusing delegated scope access_as_user ($scopeId)"
}

# The ONLY client that needs pre-authorization for a Copilot MCP plugin using
# Entra SSO is the Microsoft Enterprise token store. Microsoft 365 Copilot
# acquires the token for your MCP server through it, so this client ID must be
# added under "Expose an API" -> "Add a client application".
# This is NOT the Teams tab-SSO client-ID list; that pattern does not apply here.
# https://learn.microsoft.com/microsoft-365/copilot/extensibility/plugin-authentication-entra-sso
$ENTERPRISE_TOKEN_STORE_CLIENT_ID = "ab3be6b7-f5df-413d-ac2d-abf1e3fd9c0b"
$preAuthClients = @($ENTERPRISE_TOKEN_STORE_CLIENT_ID)

# Redirect URI required by the Copilot consent flow (Web platform).
$CONSENT_REDIRECT_URI = "https://teams.microsoft.com/api/platform/v1.0/oAuthConsentRedirect"

$apiPatch = @{
    identifierUris = @("api://$mcpAppId")
    api = @{
        requestedAccessTokenVersion = 2
        oauth2PermissionScopes = @(
            @{
                id                      = $scopeId
                value                   = "access_as_user"
                type                    = "User"
                isEnabled               = $true
                adminConsentDisplayName = "Access AgentLens governance data"
                adminConsentDescription = "Allows Microsoft 365 Copilot to call the AgentLens MCP server on behalf of the signed-in administrator. Read-only."
                userConsentDisplayName  = "Access AgentLens governance data"
                userConsentDescription  = "Allows Copilot to read your tenant's agent governance data on your behalf. Read-only."
            }
        )
        preAuthorizedApplications = @(
            $preAuthClients | ForEach-Object {
                @{
                    appId                  = $_
                    delegatedPermissionIds = @($scopeId)
                }
            }
        )
    }
    web = @{
        redirectUris = @($CONSENT_REDIRECT_URI)
    }
}

# If the SSO registration produced its own Application ID URI, append it.
# Entra's UI only shows the first URI, but multiple are supported and the
# auth config's URI must be present or token acquisition fails.
if (-not [string]::IsNullOrWhiteSpace($SsoApplicationIdUri)) {
    if ($apiPatch.identifierUris -notcontains $SsoApplicationIdUri) {
        $apiPatch.identifierUris += $SsoApplicationIdUri
    }
    Write-Step "Adding SSO Application ID URI $SsoApplicationIdUri"
}

Write-Step "Applying identifierUris, scope, redirect URI and pre-authorized client"
Invoke-GraphPatch -ObjectId $mcpObjectId -Body $apiPatch
Write-Done "Application ID URI: api://$mcpAppId"
Write-Done "Exposed scope: access_as_user"
Write-Done "Redirect URI: $CONSENT_REDIRECT_URI"
Write-Done "Pre-authorized Microsoft Enterprise token store ($ENTERPRISE_TOKEN_STORE_CLIENT_ID)"

# ---- Client secret ----
Write-Step "Creating client secret (append mode)"
$mcpSecret = New-AppSecret -AppId $mcpAppId -Description "agentlens-mcp"
Write-Done "Client secret created"
Set-KvSecret -SecretName "MCP-CLIENT-SECRET" -SecretValue $mcpSecret -Description "AgentLens-MCP client secret"

# ---------------------------------------------------------------------------
# Manual steps
# ---------------------------------------------------------------------------

Write-Section "MANUAL STEPS (a Global Administrator must do these)"

Write-Host ""
Write-Host "1. CREATE THE ENTRA SSO AUTH CONFIG (this is Step 2 of the Microsoft flow)" -ForegroundColor White
Write-Host "   The auth config lives in the Microsoft Enterprise token store, NOT in Entra." -ForegroundColor Gray
Write-Host "   It yields an AUTH CONFIG ID and an APPLICATION ID URI. You need both." -ForegroundColor Gray
Write-Host "   Easiest: VS Code + Microsoft 365 Agents Toolkit -> Add an Action ->" -ForegroundColor Gray
Write-Host "            Start with an MCP Server -> Microsoft Entra SSO -> client ID $mcpAppId" -ForegroundColor Gray
Write-Host "   Manual : Teams developer portal -> Tools -> Microsoft Entra SSO client ID registration" -ForegroundColor Gray
Write-Host "            https://dev.teams.microsoft.com/tools" -ForegroundColor Cyan
Write-Host "            Base URL must match the MCP url exactly: $McpUrl" -ForegroundColor Gray
Write-Host "   Docs   : https://learn.microsoft.com/microsoft-365/copilot/extensibility/plugin-authentication-entra-sso" -ForegroundColor Cyan
Write-Host ""
Write-Host "2. RE-RUN THIS SCRIPT WITH THE SSO APPLICATION ID URI" -ForegroundColor White
Write-Host "   Entra must list the auth config's Application ID URI or token acquisition fails." -ForegroundColor Gray
Write-Host "   ./scripts/provision-agent-mcp-app.ps1 -TenantId $TenantId -McpUrl $McpUrl ``" -ForegroundColor Cyan
Write-Host "       -SsoApplicationIdUri '<the URI from step 1>'" -ForegroundColor Cyan
Write-Host ""
Write-Host "3. PACKAGE THE AGENT WITH THE AUTH CONFIG ID" -ForegroundColor White
Write-Host "   This flips the plugin runtime from auth None to OAuthPluginVault." -ForegroundColor Gray
Write-Host "   MCP_AUTH_REFERENCE_ID=<auth config ID> AGENT_APP_ID=<guid> ``" -ForegroundColor Cyan
Write-Host "     AGENTLENS_MCP_URL=$McpUrl node scripts/package-agent.mjs" -ForegroundColor Cyan
Write-Host ""
Write-Host "4. VALIDATE THE TOKEN ON THE MCP SERVER (Step 4 of the Microsoft flow)" -ForegroundColor White
Write-Host "   Accept the SSO Application ID URI as the token AUDIENCE." -ForegroundColor Gray
Write-Host "   If you also validate the calling client, allow the Enterprise token store:" -ForegroundColor Gray
Write-Host "     $ENTERPRISE_TOKEN_STORE_CLIENT_ID" -ForegroundColor Cyan
Write-Host "   Reject anything else." -ForegroundColor Gray
Write-Host ""
Write-Host "5. GRANT ADMIN CONSENT for AgentLens-MCP" -ForegroundColor White
Write-Host "   https://entra.microsoft.com/#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/CallAnAPI/appId/$mcpAppId" -ForegroundColor Cyan
Write-Host "   Or run:  az ad app permission admin-consent --id $mcpAppId" -ForegroundColor Cyan
Write-Host ""
Write-Host "6. REMEMBER: this app grants NO data access" -ForegroundColor White
Write-Host "   All tenant read permissions live on AgentLens-Reader." -ForegroundColor Gray
Write-Host "   Run scripts/provision-reader-app.ps1 if you have not already." -ForegroundColor Gray
Write-Host ""

Write-Section "Environment block (for the MCP server)"

Write-Host ""
Write-Host "# --- AgentLens-MCP (SSO gate) ---" -ForegroundColor DarkGray
Write-Host "MCP_TENANT_ID=$TenantId"
Write-Host "MCP_CLIENT_ID=$mcpAppId"
Write-Host "MCP_AUDIENCE=api://$mcpAppId"
if ([string]::IsNullOrWhiteSpace($KeyVaultName)) {
    Write-Host "MCP_CLIENT_SECRET=$mcpSecret"
} else {
    Write-Host "# MCP_CLIENT_SECRET is in Key Vault as MCP-CLIENT-SECRET"
    Write-Host "KEY_VAULT_URI=https://$KeyVaultName.vault.azure.net/"
}
Write-Host "AGENTLENS_MCP_URL=$McpUrl"
Write-Host ""

Write-Section "Done"
Write-Done "AgentLens-MCP appId : $mcpAppId"
Write-Done "Application ID URI  : api://$mcpAppId"
Write-Warn "Grant admin consent (step 1) before sideloading the agent."
